# Generated by Django 2.2.6 on 2019-12-18 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('value', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('nickname', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.CharField(default='', max_length=300, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('nickname', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefinedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('start', models.IntegerField(blank=True, default=0, null=True)),
                ('end', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('value', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('refinedBy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='refined_by', to='annotation.RefinedBy')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('styleClass', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('selector', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Selector', to='annotation.Selector')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('motivation', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('created', models.DateTimeField(blank=True, default=None, null=True)),
                ('body', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Body', to='annotation.Body')),
                ('creator', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Selector', to='annotation.Creator')),
                ('target', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Target', to='annotation.Target')),
            ],
        ),
    ]
