# Generated by Django 2.2.6 on 2019-12-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='body',
            old_name='nickname',
            new_name='purpose',
        ),
    ]
