# Generated by Django 2.2.6 on 2019-12-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_auto_20191219_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='id_image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='id',
            field=models.URLField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
