# Generated by Django 2.2.6 on 2019-12-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20191219_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='body',
        ),
        migrations.AddField(
            model_name='annotation',
            name='body',
            field=models.ManyToManyField(blank=True, to='annotation.Body'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='id',
            field=models.URLField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
