# Generated by Django 2.2.6 on 2019-12-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_auto_20191219_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='id_image',
        ),
        migrations.AlterField(
            model_name='target',
            name='source',
            field=models.URLField(blank=True, default='', max_length=300, null=True),
        ),
    ]
