# Generated by Django 2.2.6 on 2019-12-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_auto_20191219_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='image_id',
            field=models.URLField(blank=True, default='', max_length=300, null=True),
        ),
    ]
