# Generated by Django 2.2.6 on 2019-11-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bitcoin', models.CharField(blank=True, max_length=300, null=True)),
                ('Etherium', models.CharField(max_length=300)),
                ('Litecoin', models.CharField(max_length=300)),
            ],
        ),
    ]
