# Generated by Django 2.2.6 on 2019-11-23 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BTC', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('ETH', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('LTC', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EUR', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('GBP', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('TRY', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ETFDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_title', models.CharField(blank=True, max_length=800, null=True)),
                ('assets', models.CharField(blank=True, max_length=800, null=True)),
                ('average_volume', models.CharField(blank=True, max_length=800, null=True)),
                ('ytd', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ETFDetailNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_title', models.CharField(blank=True, max_length=800, null=True)),
                ('price', models.CharField(blank=True, max_length=800, null=True)),
                ('assets', models.CharField(blank=True, max_length=800, null=True)),
                ('average_volume', models.CharField(blank=True, max_length=800, null=True)),
                ('ytd', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XAG', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('XAU', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GOOGL', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('AAPL', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('GM', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraceIndices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DJI', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('IXIC', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('INX', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ETFs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IVV', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='IVV', to='equipment.ETFDetailNew')),
                ('SPY', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='SPY', to='equipment.ETFDetailNew')),
                ('VTI', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='VTI', to='equipment.ETFDetailNew')),
            ],
        ),
    ]
