# Generated by Django 2.2.6 on 2019-11-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etfdetail',
            name='price',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
