# Generated by Django 2.2.6 on 2019-11-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrencies',
            old_name='Bitcoin',
            new_name='BTC',
        ),
        migrations.RenameField(
            model_name='cryptocurrencies',
            old_name='Etherium',
            new_name='ETH',
        ),
        migrations.RenameField(
            model_name='cryptocurrencies',
            old_name='Litecoin',
            new_name='LTC',
        ),
    ]
