# Generated by Django 2.2.6 on 2019-12-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20191203_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETFInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SPY', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('IVV', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('VTI', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='etfprice',
            name='changed_time',
        ),
        migrations.AddField(
            model_name='etfs',
            name='changed_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
