# Generated by Django 2.2.6 on 2019-11-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20191107_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BTC', models.CharField(blank=True, max_length=300, null=True)),
                ('ETH', models.CharField(max_length=300)),
                ('LTC', models.CharField(max_length=300)),
            ],
        ),
    ]
