# Generated by Django 2.2.6 on 2019-11-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_metals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metals',
            old_name='BTC',
            new_name='XAG',
        ),
        migrations.RenameField(
            model_name='metals',
            old_name='ETH',
            new_name='XAU',
        ),
        migrations.RenameField(
            model_name='metals',
            old_name='LTC',
            new_name='XRH',
        ),
    ]
