# Generated by Django 2.2.6 on 2019-12-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20191203_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='etfinformation',
            name='changed_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
