# Generated by Django 2.2.6 on 2019-11-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETFs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SPY', models.CharField(blank=True, max_length=300, null=True)),
                ('IWM', models.CharField(max_length=300)),
                ('EFA', models.CharField(max_length=300)),
            ],
        ),
    ]
