# Generated by Django 2.2.6 on 2019-11-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_etfs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etfs',
            name='EFA',
        ),
        migrations.RemoveField(
            model_name='etfs',
            name='IWM',
        ),
        migrations.AddField(
            model_name='etfs',
            name='IVV',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='etfs',
            name='VTI',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='etfs',
            name='SPY',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
