# Generated by Django 2.2.6 on 2019-11-13 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_auto_20191113_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETFDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_title', models.CharField(blank=True, max_length=800, null=True)),
                ('price', models.CharField(blank=True, max_length=800, null=True)),
                ('assets', models.CharField(blank=True, max_length=800, null=True)),
                ('average_volume', models.CharField(blank=True, max_length=800, null=True)),
                ('ytd', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='etfs',
            name='IVV',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='IVV', to='equipment.ETFDetail'),
        ),
        migrations.AlterField(
            model_name='etfs',
            name='SPY',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='SPY', to='equipment.ETFDetail'),
        ),
        migrations.AlterField(
            model_name='etfs',
            name='VTI',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='VTI', to='equipment.ETFDetail'),
        ),
    ]
