# Generated by Django 2.2.6 on 2019-11-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_auto_20191123_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencies',
            name='BTC',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrencies',
            name='ETH',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrencies',
            name='LTC',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
