# Generated by Django 2.2.6 on 2019-11-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_auto_20191123_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metals',
            name='XRH',
        ),
    ]
