# Generated by Django 2.2.6 on 2019-11-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_remove_metals_xrh'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceIndices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EUR', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('GBP', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('TRY', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
    ]
