# Generated by Django 2.2.6 on 2019-11-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0020_auto_20191123_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etfdetail',
            name='price',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
