# Generated by Django 2.2.6 on 2019-11-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0023_auto_20191123_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etfdetail',
            name='price',
        ),
    ]
