# Generated by Django 2.2.6 on 2019-10-19 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myuser', '0002_auto_20191014_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='myuser.TemplateUser')),
                ('following', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='myuser.TemplateUser')),
            ],
        ),
    ]
