# Generated by Django 2.2.6 on 2019-12-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
