# Generated by Django 2.2.6 on 2019-10-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(max_length=300)),
                ('enabled', models.BooleanField(null=True)),
                ('signifance_level', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
