# Generated by Django 2.2.6 on 2019-11-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myuser', '0005_templateuser_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USD', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('Sent_USD', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('Wealth_USD', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('BTC', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('ETH', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('LTC', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('XAG', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('XAU', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('XRH', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('GOOGL', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('AAPL', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('GM', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('EUR', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('GBP', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('TRY', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('SPY', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('IVV', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('VTI', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='myuser.TemplateUser')),
            ],
        ),
    ]
