# Generated by Django 2.2.6 on 2019-11-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20191123_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='XRH',
        ),
    ]
