# Generated by Django 2.2.6 on 2019-11-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_wallet_xrh'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='DJI',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='INX',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='IXIC',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
    ]
