# Generated by Django 2.2.6 on 2019-12-10 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0002_portfolio_is_shared'),
        ('myuser', '0009_templateuser_prediction_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_follower', to='myuser.TemplateUser')),
                ('portfolio', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='following_portfolio', to='portfolio.Portfolio')),
            ],
        ),
    ]
