# Generated by Django 2.2.6 on 2019-11-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
