# Generated by Django 2.2.6 on 2019-12-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_shared',
            field=models.BooleanField(default=True),
        ),
    ]
