# Generated by Django 2.2.6 on 2019-12-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myuser', '0007_auto_20191124_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notifier', to='myuser.TemplateUser')),
            ],
        ),
    ]
