# Generated by Django 2.2.6 on 2019-12-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='location',
            new_name='text',
        ),
    ]
