# Generated by Django 2.2.6 on 2019-12-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20191210_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='setnotification',
            name='is_bigger',
            field=models.BooleanField(default=True),
        ),
    ]
