# Generated by Django 2.2.6 on 2019-12-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0007_auto_20191124_1437'),
        ('notification', '0004_setnotification_is_bigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True)),
                ('sell_amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sell_order', to='myuser.TemplateUser')),
            ],
        ),
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True)),
                ('buy_amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='buy_order', to='myuser.TemplateUser')),
            ],
        ),
    ]
