# Generated by Django 2.2.6 on 2019-10-10 19:03

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('location', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('iban_number', models.BigIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1000000000000000), django.core.validators.MaxValueValidator(9999999999999999)])),
                ('citizenship_number', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('last_changed_password_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
