# Generated by Django 2.2.6 on 2019-10-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateuser',
            name='last_changed_password_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
