# Generated by Django 2.2.6 on 2019-10-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_auto_20191014_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateuser',
            name='biography',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='templateuser',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
