# Generated by Django 2.2.6 on 2019-11-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_auto_20191021_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateuser',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='profile'),
        ),
    ]
