# Generated by Django 2.2.6 on 2019-11-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_templateuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateuser',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
