# Generated by Django 2.2.6 on 2019-10-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_auto_20191002_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateuser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
