# Generated by Django 2.2.6 on 2019-11-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_templateuser_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateuser',
            name='iban_number',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
